Documentation:
  Enabled: false
Metrics/LineLength:
  IgnoredPatterns: ['(\A|\s)#']
  Max: 120
Layout/EmptyLineAfterGuardClause:
  Enabled: false
Layout/EmptyLinesAroundBlockBody:
  Enabled: false
Style/DoubleNegation:
  Enabled: false
Metrics/MethodLength:
  Max: 30
Metrics/BlockLength:
  Max: 30
Metrics/AbcSize:
  Max: 30
Metrics/CylocmaticComplexity:
  Max: 10