---
os: linux
language: ruby
cache: bundler
services:
  - postgresql
rvm:
  - 2.5.5
  - 2.6.3
gemfile:
  - gemfiles/Gemfile-4-2
  - gemfiles/Gemfile-5-2
  - gemfiles/Gemfile-6-0
before_install: gem install bundler
before_script:
  - bundle install
  - psql -c 'create database rails_scopy;' -U postgres
script: RAILS_ENV=test bundle exec rspec